### ISSUE TITLE
Line feed code from CRLF to LF.

### ISSUE THREAD

**Issue by AoiKagase** [novagamingcs/-AMXX-Bunker-Buster#1]
It is recommended to convert the line feed code from CRLF to LF to make it more visible on Github.

**Comment by novagamingcs** [comment]
> It is recommended to convert the line feed code from CRLF to LF to make it more visible on Github.

Sir how can i do that , new to GITHUB , where does the Option available

**Comment by AoiKagase** [comment]
I always edit in VisualStudioCode.
If you are editing in AMXX-Studio, I don't know if you have this feature.
You will have to change it in another editor.
There is also a tool to select a file and change only the line feed code.
![image](https://user-images.githubusercontent.com/26139931/102748414-7e25bf80-43a5-11eb-8dd4-e01d41f594ab.png)

**Comment by novagamingcs** [comment]
Downloading Visual studio ASAP

**Comment by AoiKagase** [comment]
VisualStudio is a bit over the top.
I recommend VisualStudio "Code".
https://azure.microsoft.com/en-us/products/visual-studio-code/
